### ISSUE TITLE
Release 0.1.1 has invalid shards.yml

### ISSUE THREAD

**Issue by peterhoeg** [chris-huxtable/syslog.cr#1]
The version in ```shards.yml``` is still 0.1.0 making it impossible to use version 0.1.1 as shards will continuously complain that ```Dependencies aren't satisfied. Install them with 'shards install'```.

Suggested fix: Bump version to 0.1.2 and update shards.yml accordingly.

**Comment by chris-huxtable** [comment]
Thanks. Now fixed. Closing.
